{% set name = "pkgconf" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pkgconf/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 0ee103cd390c3ee0e77a7a1c71dcb79a50a426fa2a648f6d07f2678c23adc5e3

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pkgconf') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson
    - ninja

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/pkgconf/{{ name }}
  license: MIT
  license_file: COPYING
  summary: package compiler and linker metadata toolkit
  dev_url: https://github.com/pkgconf/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
