context:
  version: "2.9.94"

package:
  name: pkgconf
  version: ${{ version }}

source:
  url: https://github.com/pkgconf/pkgconf/archive/pkgconf-${{ version }}.tar.gz
  sha256: 2b34aa86079e108f526ce5f3fb92cfb98c1c0f0e085c42342e5b94f69f8e46dd

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
  run_exports:
    - ${{ pin_subpackage('pkgconf') }}

tests:
  - script:
      - pkgconf --help

about:
  license: MIT
  license_file: COPYING
  summary: package compiler and linker metadata toolkit
  homepage: https://github.com/pkgconf/pkgconf
  repository: https://github.com/pkgconf/pkgconf

extra:
  recipe-maintainers:
    - danielnachun
