context:
  version: "2.9.96"

package:
  name: pkgconf
  version: ${{ version }}

source:
  url: https://github.com/pkgconf/pkgconf/archive/pkgconf-${{ version }}.tar.gz
  sha256: 82e01a2bdb5d19e6a1e15a62b890db2749d7d23ee8a75e76154a5a4e7436f749

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
  run_exports:
    - ${{ pin_subpackage('pkgconf') }}

tests:
  - script:
      - pkgconf --help

about:
  license: MIT
  license_file: COPYING
  summary: package compiler and linker metadata toolkit
  homepage: https://github.com/pkgconf/pkgconf
  repository: https://github.com/pkgconf/pkgconf

extra:
  recipe-maintainers:
    - danielnachun
