context:
  version: "3.0.6"

package:
  name: pkgconf
  version: ${{ version }}

source:
  url: https://github.com/pkgconf/pkgconf/archive/pkgconf-${{ version }}.tar.gz
  sha256: a32d9dd8fc3d1179d0755df471a561842a0f2475013da9c5cf86e38215a61380

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
  run_exports:
    - ${{ pin_subpackage('pkgconf') }}

tests:
  - script:
      - pkgconf --help

about:
  license: MIT
  license_file: COPYING
  summary: package compiler and linker metadata toolkit
  homepage: https://github.com/pkgconf/pkgconf
  repository: https://github.com/pkgconf/pkgconf

extra:
  recipe-maintainers:
    - danielnachun
