context:
  version: "2.5.0"

package:
  name: pkgconf
  version: ${{ version }}

source:
  url: https://github.com/pkgconf/pkgconf/archive/pkgconf-${{ version }}.tar.gz
  sha256: 89060c3b3e5e5c7d7101eefd6fb8df8d9bcdc6c14217390b925557b6c0064671

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
  run_exports:
    - ${{ pin_subpackage('pkgconf') }}

tests:
  - script:
      - pkgconf --help

about:
  license: MIT
  license_file: COPYING
  summary: package compiler and linker metadata toolkit
  homepage: https://github.com/pkgconf/pkgconf
  repository: https://github.com/pkgconf/pkgconf

extra:
  recipe-maintainers:
    - danielnachun
